name: linux
on: [push, pull_request]

jobs:
  test:
    name: tests
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Ruby and Crystal
        run: |
          sudo apt-get update && sudo apt-get install ruby crystal -y

      - name: Run tests
        run: |
          crystal --version
          crystal build --release --static hunaftool.rb
          ./hunaftool
          ruby tests/run-hunaftool-tests.rb ./hunaftool tests
          ruby tests/run-hunaftool-tests.rb "ruby hunaftool.rb" tests

      - name: Run tests with the old Crystal 1.6.0 from Debian "bookworm"
        run: |
          wget --quiet https://github.com/crystal-lang/crystal/releases/download/1.6.0/crystal-1.6.0-1-linux-x86_64-bundled.tar.gz
          tar -xzf crystal-1.6.0-1-linux-x86_64-bundled.tar.gz
          crystal-1.6.0-1/bin/crystal --version
          pwd
          export CRYSTAL_LIBRARY_PATH=`pwd`/crystal-1.6.0-1/lib/crystal/lib
          export LD_LIBRARY_PATH=$CRYSTAL_LIBRARY_PATH:$LD_LIBRARY_PATH
          crystal-1.6.0-1/bin/crystal build --release hunaftool.rb -o hunaftool-oldcr
          ruby tests/run-hunaftool-tests.rb ./hunaftool-oldcr tests

      - uses: actions/upload-artifact@v4
        with:
          name: hunaftool-linux-x86_64
          path: hunaftool
