name: linux
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Ruby and Crystal
        run: sudo apt-get update && sudo apt-get install ruby crystal -y

      - name: Run tests
        run: |
          crystal --version
          crystal build --release --static hunaftool.rb
          ./hunaftool
          ruby tests/run-hunaftool-tests.rb ./hunaftool tests
          ruby tests/run-hunaftool-tests.rb "ruby hunaftool.rb" tests

      - name: Run tests with the old Crystal 1.6.0 from Debian "bookworm"
        run: |
          wget --quiet https://github.com/crystal-lang/crystal/releases/download/1.6.0/crystal-1.6.0-1-linux-x86_64-bundled.tar.gz
          tar -xzf crystal-1.6.0-1-linux-x86_64-bundled.tar.gz
          crystal-1.6.0-1/bin/crystal --version
          pwd
          export CRYSTAL_LIBRARY_PATH=`pwd`/crystal-1.6.0-1/lib/crystal/lib
          export LD_LIBRARY_PATH=$CRYSTAL_LIBRARY_PATH:$LD_LIBRARY_PATH
          crystal-1.6.0-1/bin/crystal build --release hunaftool.rb -o hunaftool-oldcr
          ruby tests/run-hunaftool-tests.rb ./hunaftool-oldcr tests

      - uses: actions/upload-artifact@v4
        with:
          name: hunaftool-linux-x86_64
          path: hunaftool

  arul-suff:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Report free space
        run: |
          echo "Free space:"
          df -h

      - uses: actions/checkout@v4

      - name: Install Crystal and Zstandard
        run: |
          sudo apt-get install crystal zstd -y
          crystal build --release --static hunaftool.rb
          crystal build --release --static txt2rul.cr
          crystal build --release --static rul2aff.rb
          crystal build --release --static flagsfreq.rb

      - name: Find promising suffix rule candidates
        run: TMPDIR=. ./txt2rul words.txt > words_suff.arul

      - uses: actions/upload-artifact@v4
        with:
          name: words_suff_arul
          path: |
            hunaftool
            txt2rul
            rul2aff
            flagsfreq
            words_suff.arul

  arul-pref:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Report free space
        run: |
          echo "Free space:"
          df -h

      - uses: actions/checkout@v4

      - name: Install Crystal and Zstandard
        run: |
          sudo apt-get install crystal zstd -y
          crystal build --release --static hunaftool.rb
          crystal build --release --static txt2rul.cr
          crystal build --release --static rul2aff.rb
          crystal build --release --static flagsfreq.rb

      - name: Find promising prefix rule candidates
        run: TMPDIR=. ./txt2rul -p words.txt > words_pref.arul

      - uses: actions/upload-artifact@v4
        with:
          name: words_pref_arul
          path: |
            words_pref.arul

  dict:
    runs-on: ubuntu-latest
    needs: [arul-suff, arul-pref]
    steps:
      - uses: actions/checkout@v4

      - name: Download words_suff.arul
        uses: actions/download-artifact@v4
        with:
          name: words_suff_arul

      - name: Download words_pref.arul
        uses: actions/download-artifact@v4
        with:
          name: words_pref_arul

      - name: Install Hunspell command line tool and Ruby
        run: |
          sudo apt-get install ruby hunspell heaptrack

      - name: Assemble an affix file from the rules
        run: |
          chmod +x hunaftool
          chmod +x rul2aff
          chmod +x flagsfreq
          ./rul2aff --autoflags=90,0 words_pref.arul > words_pref.aff
          ./rul2aff --autoflags=0,90 words_suff.arul > words_suff.aff

      - name: Generate the initial dictionaries (separate for pref/suff)
        run: |
          ./hunaftool -v words_suff.aff words.txt words_suff.dic
          ls -l words_suff.dic
          wc -l words_suff.dic
          cat words_suff.aff words_suff.dic > merged.txt
          ls -l merged.txt
          ./hunaftool -v words_pref.aff words.txt words_pref.dic
          ls -l words_pref.dic
          wc -l words_pref.dic
          cat words_pref.aff words_pref.dic > merged.txt
          ls -l merged.txt

      - name: Distill a reduced .arul file
        run: |
          ./hunaftool words_suff.aff words_suff.dic words_suff_pruned.arul
          ./hunaftool words_pref.aff words_pref.dic words_pref_pruned.arul

          cat words_pref_pruned.arul words_suff_pruned.arul > words_pruned.arul

          ./rul2aff --minfreq-real=2 -g words_pruned.arul > words_pruned.aff

      - name: Generate the pruned dictionary
        run: |
          ./hunaftool -v words_pruned.aff words.txt words_pruned.dic
          ls -l words_pruned.dic
          wc -l words_pruned.dic
          cat words_pruned.aff words_pruned.dic > merged.txt
          ls -l merged.txt

      - name: Prune unnecessary rules
        run: |
          ./hunaftool words_pruned.aff words_pruned.dic words_final.aff

      - name: Generate the final dictionary
        run: |
          ./hunaftool -v words_final.aff words.txt words_final.dic
          ls -l words_final.dic
          wc -l words_final.dic
          cat words_final.aff words_final.dic > merged.txt
          ls -l merged.txt
          time hunspell -d words_final -l words.txt
          time hunspell -d words_final -l words.txt
          ruby heapusage.rb words_final words.txt

      - name: Iteratively merge flags and benchmark/test with Hunspell
        run: |
          ruby iterative-flags-merge.rb
          time hunspell -d words_final -l words.txt
          time hunspell -d words_final -l words.txt
          ruby heapusage.rb words_final words.txt

      - uses: actions/upload-artifact@v4
        with:
          name: words
          path: |
            words_pref.arul
            words_suff.arul
            words_pref.aff
            words_suff.aff
            words_pruned.arul
            words_pruned.aff
            words_pruned.dic
            words_final.aff
            words_final.dic
