name: tests
on: [push, pull_request]

jobs:
  test:
    name: tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install MSYS on Windows
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true

      - name: Install Ruby and Crystal on Windows
        if: matrix.os == 'windows-latest'
        run: |
          pacman -S mingw-w64-ucrt-x86_64-crystal
          echo "crystal=mingw-w64-ucrt-x86_64-crystal" >> $GITHUB_ENV

      - name: Install Ruby and Crystal on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update && sudo apt-get install ruby crystal -y
          echo "crystal=crystal" >> $GITHUB_ENV

      - name: Run tests
        run: |
          ${{ env.crystal }} --version
          ${{ env.crystal }} build --release hunaftool.rb -o hunaftool.exe
          ./hunaftool.exe
